#
# Copyright (c) 2014 Jan de Visser (jan@sweattrails.com)
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

import os.path
import traceback

from PyQt5.QtCore import QCoreApplication
from PyQt5.QtCore import QObject
from PyQt5.QtCore import pyqtSignal

import gripe
import gripe.db
import grumble.property
import sweattrails.device
import sweattrails.device.antfs
import sweattrails.device.exceptions
import sweattrails.device.parser
import sweattrails.qt.app.core
import grumpy.bg.bg
import grumpy.bg.job

logger = gripe.get_logger(__name__)


class DownloadManager:
    before_download = pyqtSignal(QObject)
    after_download = pyqtSignal(QObject)


class ImportedFITFile(grumble.model.Model):
    filename = grumble.property.StringProperty(is_key=True)
    status = grumble.property.BooleanProperty(default=False)


class ImportFile(grumpy.bg.job.Job):
    def __init__(self, filename):
        super(ImportFile, self).__init__()
        self.filename = filename
        user_dir = gripe.user_dir(self.user.uid())
        self.inbox = os.path.join(user_dir, "inbox")
        self.queue = os.path.join(user_dir, "queue")
        self.done = os.path.join(user_dir, "done")
        self.rejected = os.path.join(user_dir, "rejected")

    def __str__(self):
        return "Importing file %s" % self.filename

    def handle(self):
        logger.debug("ImportFile: Importing file %s", self.filename)
        f = os.path.basename(self.filename)
        parser = sweattrails.device.get_parser(self.filename)
        if not parser:
            logger.warning("No parser registered for %s", f)
            return
        parser.set_athlete(self.user)
        parser.set_logger(self)
        q = ImportedFITFile.query('"filename" =', f, parent=self.user)
        fit_file = q.get()
        dest = self.rejected
        try:
            if not fit_file:
                fit_file = ImportedFITFile(parent=self.user)
                fit_file.filename = f
                fit_file.status = False
                fit_file.put()
            try:
                parser.parse()
            except sweattrails.device.exceptions.SessionExistsError:
                # Ignore if the file was generated by the ANT download.
                # Otherwise complain.
                if "-st-antfs" not in self.filename:
                    raise
            dest = self.done
            QCoreApplication.instance().refresh.emit(None)
        except Exception:
            traceback.print_exc()
            logger.exception("Exception importing file '%s'", f)
        finally:
            if os.path.basename(os.path.dirname(self.filename)) == "queue":
                gripe.rename(os.path.join(self.queue, f), os.path.join(dest, f))
            # Set file to completed in the log:
            with gripe.db.Tx.begin():
                fit_file.status = True
                fit_file.put()


class ScanInbox(grumpy.bg.bg.ThreadPlugin):
    def __init__(self, thread):
        super(ScanInbox, self).__init__(thread)
        self.user = None
        self._setuser()
        
    def addfile(self, filename):
        self.addjob(ImportFile(filename))
            
    def addfiles(self, filenames):
        for f in filenames:
            self.addfile(f)
            
    def _setuser(self):
        # FIXME - gripe should read from the session, which qt.app.SweatTrails 
        # should manage
        user = QCoreApplication.instance().user
        if user != self.user:
            self.user = user
            user_dir = gripe.user_dir(user.uid())
            self.inbox = os.path.join(user_dir, "inbox")
            gripe.mkdir(self.inbox)
            self.queue = os.path.join(user_dir, "queue")
            gripe.mkdir(self.queue)
            self.done = os.path.join(user_dir, "done")
            gripe.mkdir(self.done)
            self.rejected = os.path.join(user_dir, "rejected")
            gripe.mkdir(self.rejected)

    def run(self):
        # We set up the paths every time since the user could have switched
        # since last time.
        self._setuser()
        if self.user:
            inbox_files = gripe.listdir(self.inbox)
            for f in inbox_files:
                if f.endswith(".fit"):
                    logger.debug("ScanInbox: Found file %s", f)
                    gripe.rename(os.path.join(self.inbox, f), os.path.join(self.queue, f))
                    self.addfile(os.path.join(gripe.root_dir(), self.queue, f))


class DownloadJob(grumpy.bg.job.Job):
    def __init__(self, manager):
        super(DownloadJob, self).__init__()
        self.manager = manager

    def __str__(self):
        return "Garmin download"

    def handle(self):
        logger.debug("Garmin download")
        self.status_message("Garmin download")
        with sweattrails.device.antfs.GarminBridge.acquire(self) as gb:
            self.manager.before_download.emit(self)
            gb.on_transport()
            self.manager.after_download.emit(self)

    # ========================================================================
    # C O N F I G  B R I D G E
    # ========================================================================

    def exists(self, antfile):
        if antfile.get_date().year < 2000:
            return True
        with gripe.db.Tx.begin():
            q = ImportedFITFile.query(ancestor=self.user)
            q.add_filter("filename", "=", self.get_filename(antfile))
            q.add_filter("status", "=", True)
            return q.get() is not None

    def select(self, antfiles):
        logger.debug("DownloadThread.select: %s files available", len(antfiles))
        selected = self.manager.selectActivities(antfiles)
        logger.debug("DownloadThread.select: %s files selected", len(selected))
        return selected

    def process(self, antfile, data):
        with gripe.db.Tx.begin():
            path = os.path.join(gripe.root_dir(),
                                gripe.user_dir(self.user.uid()),
                                "inbox",
                                self.get_filename(antfile))
            with open(path, "w") as fd:
                data.tofile(fd)
            f = self.get_filename(antfile)
            q = ImportedFITFile.query('"filename" =', f, parent=self.user)
            fitfile = q.get()
            if not fitfile:
                fitfile = ImportedFITFile(parent=self.user)
                fitfile.filename = f
            fitfile.status = False
            fitfile.put()

    def get_filename(self, antfile):
        return str.format("{0}-{1:02x}-{2}-st-antfs.fit",
                          antfile.get_date().strftime("%Y-%m-%d_%H-%M-%S"),
                          antfile.get_type(), antfile.get_size())
